version: '1'
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
services:
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    volumes:
      - shared-workspace:/opt/workspace
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
  Spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m